import { PoolClient, Pool } from 'pg';
import { getPool } from '@utils/database';
import logger from '@utils/logger';
import { Response } from 'express';

// In-memory active Server-Sent Events connections
export interface SSEClient {
  userId: string;
  res: Response;
}

export const sseClients: SSEClient[] = [];

export function addSSEClient(userId: string, res: Response) {
  sseClients.push({ userId, res });
  logger.debug(`SSE client registered for user ${userId}. Total clients: ${sseClients.length}`);
}

export function removeSSEClient(res: Response) {
  const index = sseClients.findIndex(c => c.res === res);
  if (index !== -1) {
    const userId = sseClients[index].userId;
    sseClients.splice(index, 1);
    logger.debug(`SSE client disconnected for user ${userId}. Remaining clients: ${sseClients.length}`);
  }
}

export function broadcastSSE(userId: string, eventType: string, data: any) {
  for (let i = sseClients.length - 1; i >= 0; i--) {
    const client = sseClients[i];
    if (client.userId === userId) {
      try {
        client.res.write(`event: ${eventType}\n`);
        client.res.write(`data: ${JSON.stringify(data)}\n\n`);
      } catch (err) {
        logger.error('Failed to send SSE to client; removing dead connection', err, { userId });
        sseClients.splice(i, 1);
      }
    }
  }
}

export class NotificationService {
  /**
   * Helper to format a DB notification row into the format expected by the frontend
   */
  static formatNotification(r: any) {
    let category = 'Alert';
    let tone = 'bg-blue-500';

    // Map database type to frontend tab category
    if (['AssetAssigned', 'AssetReturned', 'TransferApproved', 'TransferRejected', 'MaintenanceApproved', 'MaintenanceRejected', 'MaintenanceAssigned', 'MaintenanceResolved', 'AuditCycleCreated', 'AuditCycleClosed'].includes(r.type)) {
      category = 'Alert';
    } else if (['AllocationReturnRequested', 'TransferRequested', 'MaintenanceRequested', 'AuditItemUpdated'].includes(r.type)) {
      category = 'Approval';
    } else if (['BookingCreated', 'BookingCancelled', 'BookingReminder'].includes(r.type)) {
      category = 'Booking';
    }

    // Map type to visual tone
    if (r.type.includes('Approved') || r.type.includes('Resolved') || r.type === 'BookingConfirmed' || r.type === 'AllocationReturnApproved') {
      tone = 'bg-emerald-500';
    } else if (r.type.includes('Rejected') || r.type.includes('Cancelled')) {
      tone = 'bg-red-500';
    } else if (r.type.includes('Requested') || r.type.includes('Updated') || r.type === 'OverdueReturnAlert' || r.type === 'AuditDiscrepancyFlagged') {
      tone = 'bg-amber-500';
    } else if (category === 'Booking') {
      tone = 'bg-sky-500';
    } else {
      tone = 'bg-blue-500';
    }

    const createdAtDate = new Date(r.created_at);
    const now = new Date();
    const isToday = createdAtDate.toDateString() === now.toDateString();

    // Human-friendly time
    let time = '';
    const diffMs = now.getTime() - createdAtDate.getTime();
    const diffMins = Math.floor(diffMs / 60000);
    const diffHours = Math.floor(diffMins / 60);

    if (diffMins < 1) {
      time = 'just now';
    } else if (diffMins < 60) {
      time = `${diffMins}m ago`;
    } else if (diffHours < 24) {
      time = `${diffHours}h ago`;
    } else {
      time = createdAtDate.toLocaleDateString();
    }

    // Determine custom titles
    let title = 'Notification';
    switch (r.type) {
      case 'AssetAssigned': title = 'Asset Assigned'; break;
      case 'AssetReturned': title = 'Asset Returned'; break;
      case 'MaintenanceApproved': title = 'Maintenance Approved'; break;
      case 'MaintenanceRejected': title = 'Maintenance Rejected'; break;
      case 'BookingConfirmed': title = 'Booking Confirmed'; break;
      case 'BookingCancelled': title = 'Booking Cancelled'; break;
      case 'BookingReminder': title = 'Booking Reminder'; break;
      case 'TransferApproved': title = 'Transfer Approved'; break;
      case 'TransferRejected': title = 'Transfer Rejected'; break;
      case 'OverdueReturnAlert': title = 'Overdue Return Alert'; break;
      case 'AuditDiscrepancyFlagged': title = 'Audit Discrepancy Flagged'; break;
      default:
        title = r.type.replace(/([A-Z])/g, ' $1').trim();
    }

    return {
      id: r.id,
      userId: r.user_id,
      category,
      tone,
      title,
      detail: r.message,
      time,
      isUnread: !r.is_read,
      isToday,
      isAutoGenerated: ['BookingReminder', 'OverdueReturnAlert', 'AuditDiscrepancyFlagged'].includes(r.type),
      createdAt: r.created_at,
      relatedEntity: r.related_entity,
      relatedId: r.related_id
    };
  }

  /**
   * Create a notification using an existing transaction client.
   */
  static async createWithClient(
    client: PoolClient | Pool,
    userId: string,
    type: string,
    message: string,
    relatedEntity?: string,
    relatedId?: string
  ): Promise<void> {
    try {
      const sql = `
        INSERT INTO notifications 
          (user_id, type, message, related_entity, related_id)
        VALUES 
          ($1, $2, $3, $4, $5)
        RETURNING *
      `;
      const params = [userId, type, message, relatedEntity || null, relatedId || null];
      const result = await client.query(sql, params);
      
      if (result.rows.length > 0) {
        const formatted = this.formatNotification(result.rows[0]);
        broadcastSSE(userId, 'notification', formatted);
      }
    } catch (error) {
      logger.error('Failed to create notification with client', error, { userId, type, message });
    }
  }

  /**
   * Create a standalone notification using connection pool.
   */
  static async create(
    userId: string,
    type: string,
    message: string,
    relatedEntity?: string,
    relatedId?: string
  ): Promise<void> {
    const pool = getPool();
    await this.createWithClient(pool, userId, type, message, relatedEntity, relatedId);
  }

  /**
   * Handle an activity log event and route matching notifications to relevant users.
   * Uses getPool() directly so it never runs on a released transaction client.
   */
  static async handleActivity(
    action: string,
    targetEntity: string,
    targetId: string,
    actorUserId: string,
    metadata?: Record<string, any>
  ): Promise<void> {
    const pool = getPool();
    try {
      const actorNameResult = await pool.query('SELECT name FROM users WHERE id = $1', [actorUserId]);
      const actorName = actorNameResult.rows[0]?.name || 'Someone';

      // 1. ALLOCATIONS
      if (action === 'AllocationCreated') {
        const alloc = await pool.query(`
          SELECT a.assigned_user_id, a.assigned_dept_id, ast.asset_tag, ast.name as asset_name 
          FROM allocations a 
          JOIN assets ast ON a.asset_id = ast.id 
          WHERE a.id = $1
        `, [targetId]);
        if (alloc.rows.length > 0) {
          const { assigned_user_id, assigned_dept_id, asset_tag, asset_name } = alloc.rows[0];
          if (assigned_user_id) {
            await this.create(
              assigned_user_id,
              'AssetAssigned',
              `Asset ${asset_tag} (${asset_name}) has been assigned to you.`,
              'Allocation',
              targetId
            );
          } else if (assigned_dept_id) {
            // Notify Department Head
            const dept = await pool.query('SELECT head_user_id FROM departments WHERE id = $1', [assigned_dept_id]);
            const headId = dept.rows[0]?.head_user_id;
            if (headId) {
              await this.create(
                headId,
                'AssetAssigned',
                `Asset ${asset_tag} (${asset_name}) has been assigned to your department.`,
                'Allocation',
                targetId
              );
            }
          }
        }
      }

      else if (action === 'AllocationReturnRequested') {
        const alloc = await pool.query(`
          SELECT ast.asset_tag 
          FROM allocations a 
          JOIN assets ast ON a.asset_id = ast.id 
          WHERE a.id = $1
        `, [targetId]);
        if (alloc.rows.length > 0) {
          const { asset_tag } = alloc.rows[0];
          const managers = await pool.query("SELECT id FROM users WHERE role = 'AssetManager' AND status = 'Active'");
          for (const mgr of managers.rows) {
            await this.create(
              mgr.id,
              'AllocationReturnRequested',
              `Return approval requested for Asset ${asset_tag} by ${actorName}.`,
              'Allocation',
              targetId
            );
          }
        }
      }

      else if (action === 'AllocationReturnApproved') {
        const alloc = await pool.query(`
          SELECT a.assigned_user_id, ast.asset_tag 
          FROM allocations a 
          JOIN assets ast ON a.asset_id = ast.id 
          WHERE a.id = $1
        `, [targetId]);
        if (alloc.rows.length > 0) {
          const { assigned_user_id, asset_tag } = alloc.rows[0];
          if (assigned_user_id) {
            await this.create(
              assigned_user_id,
              'AssetReturned',
              `Your return request for Asset ${asset_tag} has been approved.`,
              'Allocation',
              targetId
            );
          }
        }
      }

      // 2. TRANSFERS
      else if (action === 'TransferRequested') {
        const transfer = await pool.query(`
          SELECT t.requested_to_type, t.requested_to_id, ast.asset_tag 
          FROM transfers t 
          JOIN assets ast ON t.asset_id = ast.id 
          WHERE t.id = $1
        `, [targetId]);
        if (transfer.rows.length > 0) {
          const { requested_to_type, requested_to_id, asset_tag } = transfer.rows[0];
          const message = `New transfer request for Asset ${asset_tag} from ${actorName}.`;

          if (requested_to_type === 'Employee') {
            await this.create(requested_to_id, 'TransferRequested', message, 'Transfer', targetId);
          } else if (requested_to_type === 'Department') {
            const dept = await pool.query('SELECT head_user_id FROM departments WHERE id = $1', [requested_to_id]);
            const headId = dept.rows[0]?.head_user_id;
            if (headId) {
              await this.create(headId, 'TransferRequested', message, 'Transfer', targetId);
            }
          }

          const managers = await pool.query("SELECT id FROM users WHERE role = 'AssetManager' AND status = 'Active'");
          for (const mgr of managers.rows) {
            if (mgr.id !== requested_to_id) {
              await this.create(mgr.id, 'TransferRequested', message, 'Transfer', targetId);
            }
          }
        }
      }

      else if (action === 'TransferApproved') {
        const transfer = await pool.query(`
          SELECT t.requested_by, t.requested_to_type, t.requested_to_id, ast.asset_tag 
          FROM transfers t 
          JOIN assets ast ON t.asset_id = ast.id 
          WHERE t.id = $1
        `, [targetId]);
        if (transfer.rows.length > 0) {
          const { requested_by, requested_to_type, requested_to_id, asset_tag } = transfer.rows[0];
          const message = `Asset ${asset_tag} transfer has been approved and allocated.`;

          await this.create(requested_by, 'TransferApproved', message, 'Transfer', targetId);
          if (requested_to_type === 'Employee') {
            await this.create(requested_to_id, 'TransferApproved', message, 'Transfer', targetId);
          }
        }
      }

      else if (action === 'TransferRejected') {
        const transfer = await pool.query(`
          SELECT t.requested_by, ast.asset_tag 
          FROM transfers t 
          JOIN assets ast ON t.asset_id = ast.id 
          WHERE t.id = $1
        `, [targetId]);
        if (transfer.rows.length > 0) {
          const { requested_by, asset_tag } = transfer.rows[0];
          await this.create(
            requested_by,
            'TransferRejected',
            `Your transfer request for Asset ${asset_tag} was rejected.`,
            'Transfer',
            targetId
          );
        }
      }

      // 3. MAINTENANCE
      else if (action === 'MaintenanceRequested') {
        const maint = await pool.query(`
          SELECT ast.asset_tag 
          FROM maintenance_requests mr 
          JOIN assets ast ON mr.asset_id = ast.id 
          WHERE mr.id = $1
        `, [targetId]);
        if (maint.rows.length > 0) {
          const { asset_tag } = maint.rows[0];
          const managers = await pool.query("SELECT id FROM users WHERE role = 'AssetManager' AND status = 'Active'");
          for (const mgr of managers.rows) {
            await this.create(
              mgr.id,
              'MaintenanceRequested',
              `New maintenance request raised for Asset ${asset_tag} by ${actorName}.`,
              'MaintenanceRequest',
              targetId
            );
          }
        }
      }

      else if (action === 'MaintenanceApproved') {
        const maint = await pool.query(`
          SELECT mr.requested_by, ast.asset_tag 
          FROM maintenance_requests mr 
          JOIN assets ast ON mr.asset_id = ast.id 
          WHERE mr.id = $1
        `, [targetId]);
        if (maint.rows.length > 0) {
          const { requested_by, asset_tag } = maint.rows[0];
          await this.create(
            requested_by,
            'MaintenanceApproved',
            `Maintenance request for Asset ${asset_tag} has been approved.`,
            'MaintenanceRequest',
            targetId
          );
        }
      }

      else if (action === 'MaintenanceRejected') {
        const maint = await pool.query(`
          SELECT mr.requested_by, ast.asset_tag 
          FROM maintenance_requests mr 
          JOIN assets ast ON mr.asset_id = ast.id 
          WHERE mr.id = $1
        `, [targetId]);
        if (maint.rows.length > 0) {
          const { requested_by, asset_tag } = maint.rows[0];
          await this.create(
            requested_by,
            'MaintenanceRejected',
            `Maintenance request for Asset ${asset_tag} was rejected.`,
            'MaintenanceRequest',
            targetId
          );
        }
      }

      else if (action === 'MaintenanceAssigned') {
        const maint = await pool.query(`
          SELECT mr.technician_name, ast.asset_tag 
          FROM maintenance_requests mr 
          JOIN assets ast ON mr.asset_id = ast.id 
          WHERE mr.id = $1
        `, [targetId]);
        if (maint.rows.length > 0) {
          const { technician_name, asset_tag } = maint.rows[0];
          if (technician_name) {
            const techUser = await pool.query("SELECT id FROM users WHERE name = $1 AND status = 'Active'", [technician_name]);
            if (techUser.rows.length > 0) {
              await this.create(
                techUser.rows[0].id,
                'MaintenanceAssigned',
                `You have been assigned to repair Asset ${asset_tag}.`,
                'MaintenanceRequest',
                targetId
              );
            }
          }
        }
      }

      else if (action === 'MaintenanceResolved') {
        const maint = await pool.query(`
          SELECT mr.requested_by, ast.asset_tag 
          FROM maintenance_requests mr 
          JOIN assets ast ON mr.asset_id = ast.id 
          WHERE mr.id = $1
        `, [targetId]);
        if (maint.rows.length > 0) {
          const { requested_by, asset_tag } = maint.rows[0];
          await this.create(
            requested_by,
            'MaintenanceResolved',
            `Maintenance for Asset ${asset_tag} is resolved and ready.`,
            'MaintenanceRequest',
            targetId
          );
        }
      }

      // 4. RESOURCE BOOKINGS
      else if (action === 'BookingCreated') {
        const booking = await pool.query(`
          SELECT rb.booked_by_id, ast.name as resource_name 
          FROM resource_bookings rb 
          JOIN assets ast ON rb.asset_id = ast.id 
          WHERE rb.id = $1
        `, [targetId]);
        if (booking.rows.length > 0) {
          const { booked_by_id, resource_name } = booking.rows[0];
          await this.create(
            booked_by_id,
            'BookingConfirmed',
            `Booking confirmed: ${resource_name}.`,
            'Booking',
            targetId
          );
        }
      }

      else if (action === 'BookingCancelled') {
        const booking = await pool.query(`
          SELECT rb.booked_by_id, ast.name as resource_name 
          FROM resource_bookings rb 
          JOIN assets ast ON rb.asset_id = ast.id 
          WHERE rb.id = $1
        `, [targetId]);
        if (booking.rows.length > 0) {
          const { booked_by_id, resource_name } = booking.rows[0];
          await this.create(
            booked_by_id,
            'BookingCancelled',
            `Booking cancelled: ${resource_name}.`,
            'Booking',
            targetId
          );
        }
      }

      // 5. AUDIT CYCLES
      else if (action === 'AuditCycleCreated') {
        const auditors = await pool.query('SELECT user_id FROM audit_cycle_auditors WHERE audit_cycle_id = $1', [targetId]);
        for (const aud of auditors.rows) {
          await this.create(
            aud.user_id,
            'AuditCycleCreated',
            `You have been assigned to a new audit cycle.`,
            'AuditCycle',
            targetId
          );
        }
      }

      else if (action === 'AuditItemUpdated') {
        const item = await pool.query(`
          SELECT ai.verification, ast.asset_tag 
          FROM audit_items ai 
          JOIN assets ast ON ai.asset_id = ast.id 
          WHERE ai.id = $1
        `, [targetId]);
        if (item.rows.length > 0) {
          const { verification, asset_tag } = item.rows[0];
          if (verification === 'Missing' || verification === 'Damaged') {
            const managers = await pool.query("SELECT id FROM users WHERE role = 'AssetManager' AND status = 'Active'");
            for (const mgr of managers.rows) {
              await this.create(
                mgr.id,
                'AuditDiscrepancyFlagged',
                `Audit discrepancy: Asset ${asset_tag} marked ${verification}.`,
                'AuditItem',
                targetId
              );
            }
          }
        }
      }

      else if (action === 'AuditCycleClosed') {
        const adminsAndManagers = await pool.query(`
          SELECT id FROM users 
          WHERE role IN ('Admin', 'AssetManager') AND status = 'Active'
        `);
        for (const u of adminsAndManagers.rows) {
          await this.create(
            u.id,
            'AuditCycleClosed',
            `Audit cycle has been closed.`,
            'AuditCycle',
            targetId
          );
        }
      }

      // 6. ADMIN USER ACTIONS (UserCreated, CategoryCreated)
      else if (action === 'UserCreated') {
        const u = await pool.query('SELECT name, email FROM users WHERE id = $1', [targetId]);
        if (u.rows.length > 0) {
          const { name, email } = u.rows[0];
          const admins = await pool.query("SELECT id FROM users WHERE role = 'Admin' AND status = 'Active'");
          for (const admin of admins.rows) {
            await this.create(
              admin.id,
              'Announcement',
              `New user created: ${name} (${email}).`,
              'User',
              targetId
            );
          }
        }
      }

      else if (action === 'CategoryCreated') {
        const cat = await pool.query('SELECT name FROM categories WHERE id = $1', [targetId]);
        if (cat.rows.length > 0) {
          const { name } = cat.rows[0];
          const admins = await pool.query("SELECT id FROM users WHERE role = 'Admin' AND status = 'Active'");
          for (const admin of admins.rows) {
            await this.create(
              admin.id,
              'Announcement',
              `New category created: ${name}.`,
              'Category',
              targetId
            );
          }
        }
      }

    } catch (err) {
      logger.error('Failed in handleActivity log router', err, { action, targetId });
    }
  }
}
