import { useGetNotificationsQuery } from '../../store/apiSlice';
import { useState } from 'react';

const filterTabs = ['All', 'Alerts', 'Approvals', 'Bookings'];

export default function NotificationsCenter() {
  const [activeTab, setActiveTab] = useState('All');
  const { data: notificationData, isLoading, error } = useGetNotificationsQuery();

  if (isLoading) return <div className="p-8 text-white">Loading notifications...</div>;
  if (error) return <div className="p-8 text-red-400">Error loading notifications</div>;

  const notifications = notificationData?.data || notificationData || [];
  
  const filteredNotifications = notifications.filter(item => {
    if (activeTab === 'All') return true;
    if (activeTab === 'Alerts' && item.category === 'Alert') return true;
    if (activeTab === 'Approvals' && item.category === 'Approval') return true;
    if (activeTab === 'Bookings' && item.category === 'Booking') return true;
    return false;
  });

  const unreadCount = notifications.filter(n => n.isUnread).length || 0;
  const todayCount = notifications.filter(n => n.isToday).length || 0;
  const autoGeneratedCount = notifications.filter(n => n.isAutoGenerated).length || 0;

  return (
    <div className="max-w-6xl mx-auto space-y-5 animate-in fade-in duration-500">
      <div className="space-y-1">
        <p className="text-sm text-slate-400">Screen 10 Activity logs &amp; Notifications</p>
        <h2 className="text-3xl font-bold text-white tracking-tight">Notifications</h2>
      </div>

      <div className="rounded-[2.5rem] border border-slate-700/70 bg-slate-800/35 shadow-2xl overflow-hidden">
        <div className="p-6 pb-4 border-b border-slate-700/70">
          <h3 className="text-2xl font-bold text-white">AssetFlow</h3>
        </div>

        <section className="p-6 lg:p-8 space-y-6">
          <div className="flex flex-wrap gap-3">
            {filterTabs.map((tab) => (
              <button
                key={tab}
                onClick={() => setActiveTab(tab)}
                className={`rounded-lg border px-6 py-2 text-[15px] font-medium transition-colors ${activeTab === tab ? 'border-emerald-300/60 bg-emerald-950/60 text-emerald-50' : 'border-slate-600/80 bg-[#3a2c2b] text-slate-100 hover:bg-[#4a3735]'}`}
              >
                {tab}
              </button>
            ))}
          </div>

          <div className="rounded-2xl border border-slate-600/70 bg-slate-900/35 overflow-hidden">
            <div className="divide-y divide-slate-700/50">
              {filteredNotifications.map((item) => (
                <article key={item.id} className="grid grid-cols-[auto_minmax(0,1fr)_auto] gap-4 items-start px-5 py-4">
                  <div className={`mt-1 h-3 w-3 rounded-sm ${item.tone || 'bg-slate-500'} shadow-[0_0_0_1px_rgba(255,255,255,0.12)]`} />

                  <div className="space-y-1">
                    <div className="flex flex-wrap items-center gap-3">
                      <h4 className="text-[16px] font-medium text-slate-100 leading-tight">{item.title}</h4>
                      <span className="rounded-full border border-slate-600/80 bg-slate-800/60 px-2.5 py-0.5 text-[11px] uppercase tracking-[0.18em] text-slate-300">
                        {item.category}
                      </span>
                    </div>
                    <p className="text-[14px] text-slate-300 leading-relaxed">{item.detail}</p>
                  </div>

                  <div className="pt-1 text-[14px] text-slate-400 whitespace-nowrap">{item.time}</div>
                </article>
              ))}
              {filteredNotifications.length === 0 && (
                <div className="p-5 text-slate-400 text-center">No notifications found.</div>
              )}
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
            <InfoCard title="Unread" value={unreadCount} tone="text-emerald-200" />
            <InfoCard title="Today" value={`${todayCount} events`} tone="text-sky-200" />
            <InfoCard title="Auto-generated" value={`${autoGeneratedCount} reports`} tone="text-amber-200" />
          </div>
        </section>
      </div>
    </div>
  );
}

function InfoCard({ title, value, tone }) {
  return (
    <div className="rounded-2xl border border-slate-600/70 bg-slate-900/30 px-5 py-4">
      <p className="text-sm text-slate-400">{title}</p>
      <div className={`mt-2 text-2xl font-bold ${tone}`}>{value}</div>
    </div>
  );
}