import { 
  useGetNotificationsQuery, 
  useMarkNotificationAsReadMutation, 
  useMarkAllNotificationsAsReadMutation,
  useDeleteNotificationMutation,
  useClearNotificationsMutation
} from '../../store/apiSlice';
import { useState } from 'react';
import { CheckCheck, Trash2 } from 'lucide-react';
import Card from '../../components/ui/Card';
import Button from '../../components/ui/Button';
import Badge from '../../components/ui/Badge';

const filterTabs = ['All', 'Unread', 'Alerts', 'Approvals', 'Bookings'];

export default function NotificationsCenter() {
  const [activeTab, setActiveTab] = useState('All');
  const { data: notificationData, isLoading, error } = useGetNotificationsQuery();
  const [markAsRead] = useMarkNotificationAsReadMutation();
  const [markAllAsRead, { isLoading: isMarkingAll }] = useMarkAllNotificationsAsReadMutation();
  const [deleteNotification] = useDeleteNotificationMutation();
  const [clearNotifications, { isLoading: isClearing }] = useClearNotificationsMutation();

  if (isLoading) return <div className="p-8 text-[var(--color-text-secondary)] text-[14px]">Loading notifications...</div>;
  if (error) return <div className="p-8 text-[var(--color-error)] text-[14px]">Error loading notifications.</div>;

  const notifications = notificationData?.data || notificationData || [];
  
  const filteredNotifications = notifications.filter(item => {
    if (activeTab === 'All') return true;
    if (activeTab === 'Unread') return item.isUnread;
    if (activeTab === 'Alerts' && item.category === 'Alert') return true;
    if (activeTab === 'Approvals' && item.category === 'Approval') return true;
    if (activeTab === 'Bookings' && item.category === 'Booking') return true;
    return false;
  });

  const unreadCount = notifications.filter(n => n.isUnread).length || 0;
  const readCount = notifications.filter(n => !n.isUnread).length || 0;
  const todayCount = notifications.filter(n => n.isToday).length || 0;
  const autoGeneratedCount = notifications.filter(n => n.isAutoGenerated).length || 0;

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-[36px] font-semibold leading-[1.15] text-[var(--color-text)] tracking-tight">
            Notifications
          </h1>
          <p className="text-[14px] text-[var(--color-text-secondary)] mt-1">
            System activity notifications, approval alerts, and return reminders
          </p>
        </div>

        <div className="flex items-center gap-2">
          {unreadCount > 0 && (
            <Button
              onClick={() => markAllAsRead()}
              disabled={isMarkingAll}
              variant="secondary"
              size="sm"
            >
              <CheckCheck className="w-4 h-4 text-[var(--color-primary)]" strokeWidth={1.75} />
              Mark all as read
            </Button>
          )}
          {readCount > 0 && (
            <Button
              onClick={() => clearNotifications({ clearRead: 'true' })}
              disabled={isClearing}
              variant="danger"
              size="sm"
            >
              <Trash2 className="w-4 h-4 text-[var(--color-error)]" strokeWidth={1.75} />
              Clear read
            </Button>
          )}
        </div>
      </div>

      {/* Filter Tabs */}
      <div className="flex flex-wrap gap-2">
        {filterTabs.map((tab) => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            className={`h-9 px-4 rounded-lg text-[13px] font-medium transition-all duration-150 ease-out select-none ${
              activeTab === tab 
                ? 'bg-[var(--color-primary-tint)] text-[var(--color-primary)] border border-[var(--color-primary)]/40' 
                : 'bg-[var(--color-surface-2)] text-[var(--color-text-secondary)] border border-[var(--color-border)] hover:text-[var(--color-text)] hover:bg-[var(--color-surface-3)]'
            }`}
          >
            {tab} {tab === 'Unread' && unreadCount > 0 ? `(${unreadCount})` : ''}
          </button>
        ))}
      </div>

      {/* Notifications List Card (§8 Cards) */}
      <Card className="p-0 overflow-hidden">
        <div className="divide-y divide-[var(--color-border)]">
          {filteredNotifications.map((item) => (
            <article
              key={item.id}
              onClick={() => item.isUnread && markAsRead(item.id)}
              className={`group flex items-start gap-4 p-4 transition-colors cursor-pointer ${
                item.isUnread ? 'bg-[var(--color-surface-2)] hover:bg-[var(--color-surface-3)]' : 'hover:bg-[var(--color-surface-2)]/50 opacity-85'
              }`}
            >
              <div className={`mt-1.5 w-2 h-2 rounded-full flex-shrink-0 ${
                item.isUnread ? 'bg-[var(--color-primary)]' : 'bg-[var(--color-border-strong)]'
              }`} />

              <div className="flex-1 min-w-0 space-y-1">
                <div className="flex flex-wrap items-center gap-2">
                  <h2 className="text-[14px] font-medium text-[var(--color-text)] leading-snug">
                    {item.title}
                  </h2>
                  <Badge status={item.category}>{item.category}</Badge>
                  {item.isUnread && (
                    <span className="inline-flex items-center h-5 px-1.5 rounded text-[10px] font-semibold uppercase tracking-wider bg-[var(--color-primary-tint)] text-[var(--color-primary-hover)]">
                      New
                    </span>
                  )}
                </div>
                <p className="text-[13px] text-[var(--color-text-secondary)] leading-relaxed">
                  {item.detail}
                </p>
              </div>

              <div className="flex items-center gap-3 pt-0.5">
                <span className="text-[12px] text-[var(--color-text-tertiary)] whitespace-nowrap">
                  {item.time}
                </span>
                <button
                  onClick={(e) => {
                    e.stopPropagation();
                    deleteNotification(item.id);
                  }}
                  className="opacity-0 group-hover:opacity-100 text-[var(--color-text-secondary)] hover:text-[var(--color-error)] p-1 transition-all"
                  title="Delete notification"
                >
                  <Trash2 className="w-4 h-4" />
                </button>
              </div>
            </article>
          ))}
          {filteredNotifications.length === 0 && (
            <div className="p-12 text-center text-[var(--color-text-tertiary)] text-[14px]">
              No notifications found in this view.
            </div>
          )}
        </div>
      </Card>

      {/* Info Summary Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <Card className="p-4">
          <p className="text-[12px] font-medium text-[var(--color-text-secondary)]">Unread Alerts</p>
          <p className="text-[28px] font-semibold text-[var(--color-text)] mt-1">{unreadCount}</p>
        </Card>
        <Card className="p-4">
          <p className="text-[12px] font-medium text-[var(--color-text-secondary)]">Today's Events</p>
          <p className="text-[28px] font-semibold text-[var(--color-text)] mt-1">{todayCount}</p>
        </Card>
        <Card className="p-4">
          <p className="text-[12px] font-medium text-[var(--color-text-secondary)]">System Generated</p>
          <p className="text-[28px] font-semibold text-[var(--color-text)] mt-1">{autoGeneratedCount}</p>
        </Card>
      </div>
    </div>
  );
}